version: '3.0'

services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/client
    ports:
      - 3000:3000
    restart: always
